#!/bin/sh

NOW="$(date +%Y%m%d)"
TAR=`which tar`
DIRS="/srv/nginx/etc/nginx /srv/nginx/www"
DEST="/mnt/skydrive/Web"

[ ! -d $DEST/$NOW ] && mkdir -p $DEST/$NOW

for dir in $DIRS
do
    # use the last part of the folder path as tarball name
    name="`basename $dir`.tar.bz2"
    cd $dir && $TAR -cjf $DEST/$NOW/$name .??* * > /dev/null 2>&1
done

#-------------------------------------
find $DEST -maxdepth 1 -type d -ctime +7 -exec rm -rf {} \;

#- vim: set ff=unix shiftwidth=4 tabstop=4 expandtab: -

