#!/bin/sh

BACKDIR="/mnt/dropbox/Linux/Gentoo"

# 定义需要备份的文件
FILES=(
    '/etc/conf.d/hostname'
    '/etc/conf.d/net'
    '/etc/default/grub'
    '/etc/fstab'
    '/etc/hosts'
    '/etc/inittab'
    '/etc/mysql'
    '/etc/nginx'
    '/etc/php'
    '/etc/portage/make.conf'
    '/etc/portage/package*'
    '/etc/samba/smb.conf'
    "/home/verdana/.ssh/config"
)

# 回到根目录
cd /

# 备份档案的文件名
archive="conf`date +%m%d.tar`"

# 删除已存在的文件
[ -f "$archive" ] && rm -f $archive
[ -f "${archive}.bz2" ] && rm -f "${archive}.bz2"

# 遍历所有的文件或目录
# 写入压缩包
for file in "${FILES[@]#?}"; do
    tar -rvpPf $archive $file
done

# 压缩备份档案，复制到备份目录
bzip2 -z9 $archive

if [ -d "$BACKDIR" ]; then
    mv "${archive}.bz2" $BACKDIR
fi

# vim: set fdm=marker ff=unix sw=4 ts=4 et:

